### PR TITLE
Macro reduction and general refactoring

### PR DESCRIPTION
**Pull request by Lmocinemod**
Also removes some more unused code, and a lingering reference to the `directxmath` package in `packages.config`. No changes to functionality.

### CODE REVIEW

**Comment by 32th-System** [comment]
I'm going to revert the XITEMS and XSTR removals because I'd like to keep XITEMS and XSTR because they're shorter and that's something that I want to be short like that. In gettext based translation systems, the gettext function is just _ so people type `_("Translatable string")`

**Comment by 32th-System** [comment]
Or I could add `using XSTR = Gui::LocaleGetStr`. Though I still want as much of 
```cpp
    locale_t LocaleGet()
    {
        return __glocale_current;
    }
    const char** LocaleGetCurrentGlossary() {
        return th_glossary_str[LocaleGet()];
    }
    const char* LocaleGetStr(th_glossary_t name) {
        return LocaleGetCurrentGlossary()[name];
    }
```
as possible to be inlined.

**Comment by Lmocinemod** [comment]
Sure, I'd be happy to alias `LocaleGetStr` to something shorter in the files that need it most. Though I can't say I'm terribly fond of the name `XSTR`. Maybe `LGS` would be better?

As for inlining, I can move the definitions of `LocaleGetCurrentGlossary` and `LocaleGetStr` to the header, and declare them `inline`. But I don't think the same can be done to `LocaleGet`, since it needs to access a private variable. (Though reverting to the macro solution obviously wouldn't fix that.)

**Comment by Lmocinemod** [comment]
Hello again. Do you have any further feedback on this PR? If so, I'm willing to make more changes/revisions.

**Comment by 32th-System** [comment]
I'm not sure if I like the name LGS. I actually like XSTR better, but perhaps we should go with _ or a single letter instead?

**Comment by Lmocinemod** [comment]
My concern with using `_` as the name is that, in many languages (not sure about C/C++), a single underscore is commonly used to "discard" a value - which linters are typically aware of, and will disable "unused variable" warnings for.

E.g. in Python:
```python
for _ in range(10):
    # (Do something ten times)
```
And I'm worried that people coming from other languages (like me) might be confused by seeing a bunch of `_(...)` calls all over the place.

As for `XSTR`... I just don't _like_ it, to be honest. 😅 It's not clear to me what exactly it's supposed to mean - "cross string", maybe? I'll admit that I don't particularly like `LGS` either, but that, at least, looks like it's supposed to be an acronym (imo). I do like your single-letter idea, though - maybe just `S` would work?

(BTW, I'm aware of the merge conflict - I'll fix it once I'm done with everything else.)

**Comment by 32th-System** [comment]
Also, while _ is in fact used in Python to mean "discard something", you also see a lot of things like `from django.utils.translation import gettext as _` for example

**Comment by Lmocinemod** [comment]
Alright, I think that's everything. I went with `S` instead of `T` because I don't want to add comments explaining why I'm `#undef`ining `T`. 😉

The commit history is kind of a mess, so feel free to squash commit / etc.

**Pull request merged**
